### ISSUE TITLE
How to avoid posts being rendered as Twig templates?

### ISSUE THREAD

**Issue by gbirke** [spress/spress#104]
I write my posts in markdown and recently I've written about Ansible, which uses curly braces for variable placeholders and a Twig-like filter syntax. My code examples  lead to missing content and errors in my posts. 

My current workaround is using `{% raw %}` and `{% endraw %}` tags around my examples, however, this introduces Twig syntax in what would be pure markdown. Is it possible to instruct Spress to convert markdown to HTML, but treat the resulting HTML not as a Twig template? When I insert `avoid_renderizer` in the page metadata, the page gets rendered without layout.

**Comment by yosymfony** [comment]
Hi @gbirke. I had that problem with the Spress's page and I had to instroduce a little of Twig syntax. Indeed `avoid_renderizer` attribute avoid both the Twig efect and the layout process
