### ISSUE TITLE
.htaccess not being included in build

### ISSUE THREAD

**Issue by nikolaposa** [spress/Spress#107]
I have a `.htaccess` file in my content directory which is not being included in the resulting build directory. 

I think that the reason is that `ignoreDotFiles(false)` statement is missing somewhere over here, because Symfony `Finder` ignores dot files by default: https://github.com/spress/Spress/blob/master/src/Core/DataSource/Filesystem/FilesystemDataSource.php#L148

**Comment by yosymfony** [comment]
Hi. Yes, I have the same issue. I'm going to see

**Comment by yosymfony** [comment]
Fixed. It was just a `ignoreDotFiles`. Your feeling was right 😄
