### ISSUE TITLE
Add support for league/commonmark

### ISSUE THREAD

**Issue by colinodell** [spress/spress#108]
[`league/commonmark`](http://commonmark.thephpleague.com/) is a modern Markdown parser which supports custom syntax and has [several community-built extensions](https://github.com/thephpleague/commonmark#community-extensions).

**Comment by yosymfony** [comment]
Hello @colinodell. What are the differences/advantages over http://parsedown.org/ or https://michelf.ca/projects/php-markdown/ (they are the built-in Markdown converters)
You may extend Spress with support for this Markfown parser by plugins
