### ISSUE TITLE
builtin web server to serve also PHP pages? 

### ISSUE THREAD

**Issue by zontarian** [spress/Spress#109]
Hi,
we are planning to use Spress to generate a mostly-static site, but some pages need to call some custom PHP code before loading. To be more precise, we need to execute a system command (which just sends some bytes over UDP) when the user pushes a HTML button and change pages.
Of course we could to it with JQuery/Angular or something like this.. but..

Our customer is on a budget, and so we are even more on a real budget and we must go with the fastest solution.
One that I've found is to use Spress to generate all the static pages based on some layouts, even the pages that contain some PHP code (with php extension). It works: twigs treat the PHP page as a text one (I've edited the config file) and parses it and generates the correct html with style etc, maintaining the PHP tags..

Problem is, the built in server doesn't parse php pages, they get downloaded instead of executed. If I rsync them to my deployment server (nginx+php-fmp), they work as expected.

So, is there a way to make the builtin web server work with php pages? It would speed up the development, and since we are on a tight budget this is paramount.
Thanks
Z

PS.. first I wanted to make something more clean, maybe a Twig Extension, but i didn't find how to integrate them in Spress, so I decided to go for the dirtiest, and besides I want something to be executed at runtime, not at generation time, so again, not sure if this would have been appropriate nonetheless.

Any better idea is welcome, anyway

**Comment by yosymfony** [comment]
Hi. The built-in server is designed for serving static content in a development environment. In your case, you can use the PHP built-in server pointing to `build` folder as rootdocument. E.g: `php -S localhost:8000`

For the other part of the question, you can create a Twig extension as a Spress plugin: http://spress.yosymfony.com/docs/developers/renderizer/

**Comment by yosymfony** [comment]
More details about the built-in server of PHP http://php.net/manual/en/features.commandline.webserver.php

**Comment by zontarian** [comment]
Thanks.. at the moment I've reduced the number of PHP pages, using more JS :) 
And besides, if I launch the standalone php server, it will serve pages on a different port as the one of the Spress built in server, so the site links won't be usable, correct? 

I will look at the plugin, thanks
