### ISSUE TITLE
Composer install command

### ISSUE THREAD

**Issue by shdev** [spress/Spress#110]
This is just a request for an enhancement.
I know that you can install composer.lock with

```bash
spress spress upda:plug --prefer-lock --prefer-lock
```

But it is not obvious. I would like to have a own command for it.
At least a mention in the documentation.

**Comment by yosymfony** [comment]
@shdev I just merged your doc PR

**Comment by yosymfony** [comment]
Can I close this issue?

**Comment by shdev** [comment]
Thanks for merging. I would like to have it as a separated command. but maybe I try to make a pull request for it.
