### ISSUE TITLE
Make use of more than one theme at a time?

### ISSUE THREAD

**Issue by Webslung** [spress/spress#114]
Is it possible to place more than one theme in at a time? I've tried doing it like so:

```
themes:
  name: 'theme-01'
  name: 'theme-02'
```

but only the first theme will be used. Is this working as expected? The documentation shows a `theme-01` and `theme-02` on this [page](http://spress.yosymfony.com/docs/themes/) but I may be reading too far into it.

What I was hoping to achieve was a cascading effect where if an include or layout didn't exist in the first, Spress would look in the second. Thanks!

**Comment by yosymfony** [comment]
Hello @Webslung. You can have several themes installed but only one of them can be in use.
