### ISSUE TITLE
 New blog list page: "A previous item exists with the same id: "index.html". Generator: "pagination""

### ISSUE THREAD

**Issue by melat0nin** [spress/spress#116]
I'm trying to create a new static page by duplicating and adapting the index.html file in the generated site that comes with `clean-blog-theme` (I would like the list of blog posts to be on a separate page from the index, e.g. on blog.html) but I receive this error:

``A previous item exists with the same id: "index.html". Generator: "pagination" ``

I've tried making sure only one page uses the pagination generator but it doesn't help. Where are these ids stored? Is something being cached?

Any help appreciated!

**Comment by yosymfony** [comment]
There is no cache for those ids. It's seems like something is generating another `index.html` page. Where is located the generator? in `blog` folder?
