### ISSUE TITLE
Move pages source into a "_pages" directory

### ISSUE THREAD

**Issue by ocubom** [spress/Spress#23]
The root folder can contain other files or folders (README, LICENSE, assets preprocessors) without taking care about exclude patterns on configuration file.

Optionally, the '_' in all folders can be suppresed: special cases are not longer needed.

![spress-pages](https://cloud.githubusercontent.com/assets/184187/4782391/61e437c8-5cef-11e4-83b5-a12eb040d0f8.png)
.

**Comment by lury** [comment]
imho this ticket should be closed - changes are applied in 2.0 file structure.
