### ISSUE TITLE
Support .twig extention

### ISSUE THREAD

**Issue by peterfox** [spress/Spress#28]
Currently even though html and even markup files use twig syntax in files it appears you have to stick with the original extension? It would be better to be able to either config this or use files that are formatted as .html.twig etc. so that editors such as PHPStorm know how to correctly format the file as you work with it.

**Comment by carbontwelve** [comment]
:+1: to this. I thought the `layout_ext` config setting was for this functionality, but it appears not.

**Comment by yosymfony** [comment]
@carbontwelve Spress 2.1.0  will incorporate this feature. `layout_ext` is not related with this issue. It is neccesary to add a new Converter for dealing `.twig` files and set the `html` exetension as output
