### ISSUE TITLE
curl command not working in getting started

### ISSUE THREAD

**Issue by Remo** [spress/Spress#35]
Here's a command using curl to download the phar file. Unfortunately it didn't work for me as there's a redirect which curl doesn't follow by default..
http://spress.yosymfony.com/docs/getting-started/

I had to use something like `curl -LOS https://github.com/spress/Spress/releases/download/v1.1.0/spress.phar`

**Comment by yosymfony** [comment]
You are right. without L option you get an error. Documentation fixed. Thank you.
