### ISSUE TITLE
default port of spress doesn't match spresso theme

### ISSUE THREAD

**Issue by Remo** [spress/Spress#36]
It's not a big deal to figure out, but if things aren't working at the beginning you'll scare away some people. When I just follow the getting started guide I'll get a page at localhost:4000, but the theme will generate absolute urls pointing to localhost:8080

I'd suggest to either remove the domain from the asset links, change the port to 4000 in the spresso theme https://github.com/yosymfony/Spress-theme-spresso/blob/master/config.yml or make spress --server use 8080 by default.

**Comment by yosymfony** [comment]
Yes. I'll change `config.yml` file of Spresso theme with a empty value for `url` variable.

**Comment by yosymfony** [comment]
Fixed. A new [release of Spress is out](http://spress.yosymfony.com/releases/2015/02/25/spress-1-1-1-is-out/). Thank you!
