### ISSUE TITLE
[Feature] Dynamic category pages

### ISSUE THREAD

**Issue by Remo** [spress/Spress#37]
Maybe I'm missing something, but so far I haven't been able to find any way to create dynamic pages per category. I'm using custom permal links with this option `permalink: "/:categories/:title"`.

It's feel natural to be able to open `/category-1` to see all pages that belong to this category. While it's easy to fetch all pages that belong to that category, I haven't seen a way to create those pages automatically. 

Am I missing something or is this something that could be added in the future?

**Comment by yosymfony** [comment]
Currently there no easy way to do it. You need to create a plugin. I'm thinking how to resolve this issue for Spress 2.0.

**Comment by lury** [comment]
+1

this is the only issue stopping me from using spress - i need taxonomy pages with pager.

Any info how to do this via plugin?

**Comment by yosymfony** [comment]
@lury that feature will come with Spress 2.0.0 beta
