### ISSUE TITLE
Multi-language support for post title

### ISSUE THREAD

**Issue by zither** [spress/Spress#38]
For example: 2015-03-12-spress-is-a-static-site-generator.md
```
---
layout: post
title: Spress 静态网站生成器
categories: [Blog]
---
```
expect:
/blog/2015/03/12/spress-is-a-static-site-generator/index.html

but the actual result is：
/blog/2015/03/12/spress--/index.html

Front-matter's title may be non-English characters.
I think using relative path to generate url is better than  front-matter's title.

**Comment by yosymfony** [comment]
Currently if you set a title attribute in frontmatter will replace the original title. This case would be a good point to improvement for Spress 2.0.0
