### ISSUE TITLE
Use erusev/parsedown instead of markdown

### ISSUE THREAD

**Issue by mickaelandrieu** [spress/Spress#40]
Parsedown supports more and seems to be more performant than any other PHP markdown parser

**Comment by yosymfony** [comment]
Look nice http://parsedown.org/

**Comment by yosymfony** [comment]
To enabled add the following line to your `config.yml` file of your Spress 2.0 site (see #41 ): `parsedown_actived: true`

**Comment by mickaelandrieu** [comment]
@yosymfony thank you for this addition :) (you can close btw)

**Comment by lury** [comment]
```parsedown actived``` ?

you mean activated / active - right? ;)

**Comment by yosymfony** [comment]
yes! my bad :)

**Comment by yosymfony** [comment]
Fixed typo 466deaf4351457a2d0b0ff0fc7f67c9abae2584f
