### ISSUE TITLE
Generators for creating new content

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#45]
Generators are used for generating new items of content. Generators can be used to create a tag or category index page dynamically. A good example of this is [`PaginationGenerator`](https://github.com/spress/Spress/blob/master/src/Core/ContentManager/Generator/Pagination/PaginationGenerator.php) whose responsibility is to generate multiple pages around a set of items like posts or any other collection (see #43 ).

A Generator must implement [`GeneratorInterface`](https://github.com/spress/Spress/blob/master/src/Core/ContentManager/Generator/GeneratorInterface.php):

```
namespace Yosymfony\Spress\Core\ContentManager\Generator;

interface GeneratorInterface
{
    /**
     * Generate items.
     *
     * @param \Yosymfony\Spress\Core\DataSource\ItemInterface $templateItem The template item where generator was declared.
     * @param array                                           $collecions   An array with the collection name
     *                                                                      as a key and collection's item as value.
     *
     * @return Yosymfony\Spress\Core\DataSource\ItemInterface[]
     */
    public function generateItems(ItemInterface $templateItem, array $collecions);
}
```
Generators are performed just after Data Sources are loaded.

**Comment by lury** [comment]
:+1:
