### ISSUE TITLE
spress.after_convert_posts thrown way to early - before all posts were converted

### ISSUE THREAD

**Issue by lury** [spress/Spress#53]
Hi,

i've made a really simple plugin for spress, which basically echoes name of event for every event - baby steps to create more sophisticated plugin.

Repo is here (it's a result of `spress new:site ./ spresso` + `spress new:plugin` + my mini changes in plugin code): https://github.com/lury/spress-test-plugin - it's not a separate plugin - sorry ;)

When you run `spress site:build`, according to specs, you should see `spress.after_convert_posts` after generating all posts, but it's fired right after first post has been processed.

```
plugin git:(master) spress site:build
Starting...
Environment: dev.
-+- spress.start -+-
-+- spress.before_convert -+-
-+- spress.after_convert -+-
-+- spress.after_convert_posts -+- <<<< this should be later on (next marker)
-+- spress.before_convert -+-
-+- spress.after_convert -+-
-+- spress.before_convert -+-
-+- spress.before_convert -+-
-+- spress.before_convert -+-
-+- spress.before_convert -+-
-+- spress.after_convert -+-
-+- spress.before_convert -+-
-+- spress.after_convert -+-
-+- spress.before_convert -+-
-+- spress.after_convert -+- <<<< here is the last convert event, so after_conver_posts should fire here - right?
-+- spress.before_render -+-
-+- spress.after_render -+-
-+- spress.before_render -+-
-+- spress.after_render -+-
-+- spress.before_render -+-
-+- spress.after_render -+-
-+- spress.before_render -+-
-+- spress.after_render -+-
-+- spress.before_render -+-
-+- spress.after_render -+-
-+- spress.before_render_pagination -+-
-+- spress.after_render_pagination -+-
-+- spress.finish -+-
Total posts: 1
Processed posts: 1
Drafts post: 0
Total pages: 7
Processed pages: 4
Other resources: 7
```

### Is this expected and correct behaviour?

docs says:
```
The spress.after_convert_posts is thrown after convert all posts.
```
and name of the event implies the same, so it looks like a bug to me.

**Comment by lury** [comment]
hmm, this event was removed in 2.0 #49 
still, this looks like a bug ;)

**Comment by yosymfony** [comment]
Yes, that looks like a bug of branch 1.1.

**Comment by yosymfony** [comment]
That's already fixed in Spress 2.x
