### ISSUE TITLE
Renderizer error with min files

### ISSUE THREAD

**Issue by enzolutions** [spress/Spress#62]
I am trying to migrate my page from Spress 1.x to 2.x

But when I try add assets css and js minified files produce and error with Renderizer, I resolve unminified some css files but I still get and error with Modernizer js (2.7.1) library event that it's not minified.

This the error I get when I try to build my site.

```
[Yosymfony\Spress\Core\ContentManager\Renderizer\Exception\RenderException]
  Error during lexing or parsing of a template in "assets\/js\/vendor\/modernizr-2.7.1.custom.min.js".



  [Twig_Error_Syntax]
  Unclosed comment in "@dynamic/content" at line 77.
```

**Comment by yosymfony** [comment]
See section "Avoids renderizer in some files" http://spress.yosymfony.com/docs/themes/

**Comment by enzolutions** [comment]
Thanks for your link to documentation, but I set my config.yml file to add the option

```
avoid_renderizer: true
```

But doesn't work at all.

**Comment by yosymfony** [comment]
You need to add the attribute at the front-matter block of the file

**Comment by enzolutions** [comment]
Could you provide an example

**Comment by yosymfony** [comment]
Open the `.min.js` file and add the following at the beginning:
```
---
avoid_renderizer: true
---
```
