### ISSUE TITLE
Items in collections should be ordered

### ISSUE THREAD

**Issue by jjk-jacky** [spress/Spress#63]
Currently items in a collection aren't in any given order, which basically means
they're "useless" since they're pretty much in a random order. For example, if
one tries to loop over them to make an RSS feed, via e.g:

    for post in site.posts

It won't give proper results, since again there's no order. I'm not really
familiar with Spress codebase so I'm not sure on the "how" but I believe this
could be addressed in ContentManager->process(), after looping over $items and
before looping over $itemsGenerator, it should be possible to loop over
$this->itemsByCollection, and then apply a default order which could be set from
config, e.g:

    collections:
        posts:
            sort_by: date
        projects:
            sort_by: title
            sort_type: ascending

Of course it also means this default sort order will be of use in generators,
though it'll still be possible to define a custom sort order alongside a
generator, as is the case today.

Additionally, I'd also like it a lot if, after this default sorting, all items
could get attributes referring to the previous & next items in the collection
(as per this default sort order). That way, when generating the page for one item
in a collection, it'd be possible to have links to the previous and/or next item
in said collection.

This might not be as necessary to make items usable, but it'd be nice to have;
and I won't lie, I'm needing this to convert a site from jekyll to Spress, so
yeah.

**Comment by yosymfony** [comment]
Nice feature. Ok, the collection's attributes are the right place to define how its items will be sorted. `sort_by` and `sort_type` attributes will have the same behaviour that defined in [pagination generator](http://spress.yosymfony.com/docs/pagination).

**Comment by yosymfony** [comment]
about "referring to the previous & next items", you mean, that we need to expose two new attributes, like `next_item_url` and `prior_item_url`. e.g: `page.next_item_url`

**Comment by jjk-jacky** [comment]
> about "referring to the previous & next items", you mean, that we
> need to expose two new attributes, like `next_item_url` and
> `prior_item_url`. e.g: `page.next_item_url`

Yes; Ideally this would allow to do links to the previous/next items, so
I think at least 4 new attributes would be needed: 'previous_item_url' &
'previous_item_title' for the URL & title of the previous item, and
similarly 'next_item_url' & 'next_item_title' for the next one.

So one can link to the previous/next item, using e.g. its title as link.

Or maybe there could be a page.previous_item & page.next_item, allowing
to access all the items' attributes/variables (via e.g.
page.next_item.url)

**Comment by yosymfony** [comment]
Features #67 and #69 have been merged to the master branch
