### ISSUE TITLE
Can't generate JSON file on plugin

### ISSUE THREAD

**Issue by loopion** [spress/Spress#66]
I was trying to create a JSON file with some information (title, tags, url, description) so I first tried with the twig json_encode but it didn't worked well as I needed a parent pages node and then I tried to create it via plugin but as it's already a loop within EventSubscribers I didn't find out how to do it.

Example of my plugin which doesn't render the correct JSON:

`
    public function onAfterRenderPage(RenderEvent $event)
    {
      $page = $event->getAttributes();
      if($page['collection'] == 'videos') {
        array_push($json_array, array('title' => $page['title'], 'text' => $page['title'], 'tags' => "none", 'url' => urldecode($page['url'])));
        file_put_contents("./build/content.json", json_encode($json_array), FILE_APPEND);
      }
`

The result should look like this: 

`
      {"pages": [
           {"title": "About me", "text": "", "tags": "jQuery HTML5 CSS", "url": "http://www.myurl.com/about-me"},
           {"title": "Portfolio page", "text": "My Description of this item", "tags": "JavaScript", "url": "http://www.myurl.com/portfolio"}
      ]}
`
Any help would be welcome.

**Comment by yosymfony** [comment]
well, you could use [`spress.finish` event](http://spress.yosymfony.com/docs/developers/events-list/#finishevent) that contains a global vision of items:
```php
$subscriber->addEventListener('spress.finish', 
    function(FinishEvent $event)
    {
        $items = $event->getItems();
        foreach ($items as $item) {
            if ($item->isBinary()) {
                continue;
            }

            $attributes = $item->getAttributes();
            if($attributes['collection'] == 'videos' {
                // ...
            }
        }
        // write to file or anything else
    });
```

**Comment by loopion** [comment]
Thank you! It's working properly now. :+1:
