### ISSUE TITLE
Taxonomies

### ISSUE THREAD

**Issue by Swader** [spress/Spress#68]
In the docs, the taxonomy instructions for listing out categories at the end of the post don't work. But if we use the original approach which was still used in Sculpin, then it does work. So this works:

```
   {% if page.categories %}
    <p class="categories text">
        <span>Categories:</span>
        {% for category in page.categories %}
        <a href="{{ site.url }}/blog/categories/{{ category|url_encode(true) }}">{{ category }}</a>
        {% endfor %}
    </p>
    {% endif %}
    {% if page.tags %}
    <p class="tags text">
        <span>Tags:</span>
        {% for tag in page.tags %}
        <a href="{{ site.url }}/blog/tags/{{ tag|url_encode(true) }}">{{ tag }}</a>
        {% endfor %}
    </p>
    {% endif %}
```

Recommend updating the taxonomies section significantly to make it 100% bulletproof - because even with this, and with setting up taxonomy permalinks to `/blog/categories/:name` for cats and similar for tags, I got 404 errors.

**Comment by yosymfony** [comment]
I'm working on this issue

**Comment by yosymfony** [comment]
Where are you using prior snippet of code? `site.tags` and `site.categories` are special variables that contains post items organized by tags and categories regardless of taxonomy generator.

**Comment by yosymfony** [comment]
This work fine. Keep in mind that `page` represents the current item:
```Twig
{% set categoryList = [] %}
<ul>
{% for category in site.categories %}
	{% for item in category %}
		{% for categoryName, url in item.terms_url.categories %}
			{% if categoryName not in categoryList | keys %}
				{% set categoryList = categoryList | merge({ (categoryName) : url }) %}

				<li><a href="{{ url }}">{{ categoryName }}</a></li>
			{% endif %}
		{% endfor %}
	{% endfor %}
    
{% endfor %}
</ul>
```
