### ISSUE TITLE
Category aggregation for customized contents

### ISSUE THREAD

**Issue by taylorren** [spress/Spress#70]
I have created a customized content type:

    reports:
        output: true

When I create a few "report" items, and assign some new categories to those items:

> ---
> 
> layout: "page"
> title: "译者前言"
> categories: ["projects", "articles"]
> 
> ---
> 
> #My project 1

, the `categories` assigned to those posts are not "grabbed" with the following code:

```
{% set categoryList = [] %}
<ul>
{% for category in site.categories %}
  {% for item in category %}
    {% for categoryName, categoryUrl in item.terms_url.categories %}
      {% if categoryName not in categoryList | keys %}
        {% set categoryList = categoryList | merge({ (categoryName) : categoryUrl }) %}

        <li><a href="{{ categoryUrl }}">{{ categoryName }}</a></li>
      {% endif %}
    {% endfor %}
  {% endfor %}

{% endfor %}
</ul>

```
But the "new" categories are listed in the `build/categories/new` folder so a direct access to it works. What I need is an index page so that "mysite/categories" will show all the categories in all my posts, projects, reports. 

Any hints

**Comment by yosymfony** [comment]
`site.categories` only works with items belong to `posts` collection

**Comment by taylorren** [comment]
OIC. Is there a plan to expand the `site.categories` to include other 
customized collections?

在 16/02/15 00:53, Yo! Symfony 写道:
