### ISSUE TITLE
Two posts with the same date

### ISSUE THREAD

**Issue by taylorren** [spress/Spress#71]
I have two posts with the same date:

    2015-09-29-naming-rrq.md
    2015-09-29-naming-rsh.md

The generated output only has one entry under article/page/2015/09/29index.html

What is this problem?

**Comment by yosymfony** [comment]
Can you provide more details about your permalink configuracion? Are you using a `title` attribute in those post?

**Comment by yosymfony** [comment]
Ser http://spress.yosymfony.com/docs/permalinks/

**Comment by taylorren** [comment]
I don't have permalink settings in config.yml or src/index.html. It is the default setting after new:site

**Comment by taylorren** [comment]
I think I have found the issue: the two posts are having Chinese as its title so when slugging the title to be used in permalink, all Chinese characters became null. As a matter of fact, I must use Chinese as my post titles. 

Any hint?

**Comment by yosymfony** [comment]
Maybe "Preserve title from filename in permalinks" section could help you http://spress.yosymfony.com/docs/writing-posts/

**Comment by taylorren** [comment]
Yes, this is working fine. Thanks!
