### ISSUE TITLE
Using spress anywhere on command line

### ISSUE THREAD

**Issue by jorenmartijn** [spress/Spress#75]
Hi,

Just wondering how to use spress from the command line like the laravel command.
Does anyone know how to do that? If I copy /bin/spress to /usr/local/bin/ and type spress in the command line it asks me to run composer update first, but that doesn't work in the new location.

Regards,
Joren

**Comment by yosymfony** [comment]
Are you using `.phar` file? I have `spress.phar` at `/usr/local/bin` and work fine for me.
If you are using the source code, you need to create a symbolic link.

**Comment by jorenmartijn** [comment]
I've build the phar file using Box, copied it to /usr/local/bin and it gives me these errors:

```
PHP Fatal error:  Cannot redeclare composerRequire0cd75bdd1fa15afefe7e0cdf3f1712cd() (previously declared in phar:///usr/local/bin/spress.phar/vendor/composer/autoload_real.php:56) in /Server/Spress/vendor/composer/autoload_real.php on line 59

Fatal error: Cannot redeclare composerRequire0cd75bdd1fa15afefe7e0cdf3f1712cd() (previously declared in phar:///usr/local/bin/spress.phar/vendor/composer/autoload_real.php:56) in /Server/Spress/vendor/composer/autoload_real.php on line 59
```

**Comment by yosymfony** [comment]
Move the resulting `.phar` file to another folder. That error is threw if you are running `spress.phar` in the same folder of Spress source code because conflicts with Composer loader.

**Comment by jorenmartijn** [comment]
I think it worked. Thanks!
