### ISSUE TITLE
/:basename permalink variable contains .html when using *.html.twig

### ISSUE THREAD

**Issue by KristiyanHristov** [spress/Spress#78]
#### Expected behavior
Spress should generate: `index.html`, `about.html` ...

#### Actual behavior
Spress generates `index.html.html`, `about.html.html` ...

#### Steps to reproduce the behavior
1. make sure all layouts and pages have `.html.twig` extension
1. add `permalink: /:path/:basename.:extension` in `config.yml`

#### Environment information
**Spress Version:** 2.1.0

#### Probable cause
The `/:basename` permalink variable contains `.html` when using the `map_converter_extension` feature introduced in Spress v2.1.0

**Comment by yosymfony** [comment]
Ok. I will review it.

**Comment by yosymfony** [comment]
Related with #73

**Comment by yosymfony** [comment]
Thanks for the good explanation of this bug :smile:

**Comment by KristiyanHristov** [comment]
> Thanks for the good explanation of this bug :smile:

thanks for the quick response
