### ISSUE TITLE
Substr "---" in yaml string cause builder crash

### ISSUE THREAD

**Issue by urmaul** [spress/Spress#82]
If you edit any post content and add string like this to meta fileds:

```yaml
foo: 'bar---baz'
```

site:build creashes with error like this:

```
  [Symfony\Component\Yaml\Exception\ParseException]                  
  Malformed inline YAML string ('bar) at line 6 (near "foo: 'bar").
```

**Comment by yosymfony** [comment]
Seems that [`AttributeParser`](https://github.com/spress/Spress/blob/master/src/Core/DataSource/Filesystem/AttributeParser.php) needs a review. I'm working on that

**Comment by yosymfony** [comment]
Fixed. Thank you
