### ISSUE TITLE
Same tags on different languages cause builder crash

### ISSUE THREAD

**Issue by urmaul** [spress/Spress#83]
Imagine you have two posts. One has tag "bash" and another one has tag "баш", which transliterates to "bash".

In this case TaxonomyGenerator tries to generate 2 tag pages with same permalink and builder crashes with error:

```
  [RuntimeException]
  A previous item exists with the same id: "tags/bash/index.html". Generator: "taxonomy".
```

BTW case insensitivity doesn't work with cyrillic characters too. TaxonomyGenerator thinks "баш" and "баШ" are different tags and fails with same error.

**Comment by yosymfony** [comment]
A possible solution for this issue could be to add a suffix at the end of each term in case of conflict. e.g:

Term | Path
---- | ----
bash | `/bash`
баш  | `/bash-1`

And if the term "баш" is found before "bash" term then the result will be the following:

Term | Path
---- | ----
баш  | `/bash`
bash | `/bash-1`

**Comment by urmaul** [comment]
Or just to merge posts to one collection. In most cases both terms have same meaning.

**Comment by yosymfony** [comment]
Bug fixed and merged on master. Thanks for the report
