### ISSUE TITLE
Documentation for generating image gallery

### ISSUE THREAD

**Issue by raspi** [spress/Spress#85]
Documentation should contain how to generate simple image gallery with images with descriptions with possibility of multi-layer deep folder structure.

**Comment by yosymfony** [comment]
right, but this is a subject of [yosymfony/Spress.yosymfony.com](https://github.com/yosymfony/Spress.yosymfony.com) repo.

**Comment by raspi** [comment]
Moved to https://github.com/yosymfony/Spress.yosymfony.com/issues/13
