### ISSUE TITLE
Find page url by attribute

### ISSUE THREAD

**Issue by XenoneX** [spress/Spress#86]
Hello.
I can't understand is there any way to get url of page on other page, by typing something like "{{ page_title | find_in_pages }}"? Because I tried to add twig extension, but it comes on the start, so on site.collections.pages array there is no pages at all. Can anyone get me some advice with that? Or there is some other way to do this?

I need a tag to get url of other page on rendered page.

Sorry for my poor english.

**Comment by yosymfony** [comment]
Hi. There's not a built-in method to find a page or post by an attribute, but you can take advantage of loop with conditions of Twig:

```twig
{% for page in site.pages if page.your_attribute = 'value' %}
    <a href="{{ page.url }}">{{ page.title }}<i>
{% endfor %}
```
Note that `site.collections` only contains information about collections itself. Items of a collection are available at `site.name_of_collection.` e.g: `site.post` or `site.pages`. See http://spress.yosymfony.com/docs/collections/
