### ISSUE TITLE
Add option to config to avoid_renderizer for types of files

### ISSUE THREAD

**Issue by knorthfield** [spress/Spress#91]
e.g. CSS

**Comment by yosymfony** [comment]
You already can use `avoid_renderizer` attribute with `css` files like in `js` files. You only need to add that one to the front matter block or metadata file

**Comment by yosymfony** [comment]
This will be a good feature for Spress 2.2.0

**Comment by jevets** [comment]
Would love to see this feature. It'd be great to exclude an entire directory, as well as file types as @knorthfield suggests.

Examples:

- Package managers w/ directories like `bower_components` or `node_modules`, with many files that would throw the renderizer.
- Inherited a large, nasty bunch of theme jungle files, and it's simply impractical to add a front matter or `.meta` files.

In my case, I'd want the directories/files copied over during build, just not renderized.

**Comment by yosymfony** [comment]
For this feature I propose a new configuration key called `avoid_renderizer` (this belong to site scope instead of page scope) with two sub-keys: `filename_extension` and `path`. The value of those ones is an array with filename extensions and directories respectively in which to apply the "avoid_renderizer" feature. e.g:

```yaml
# config.yml
avoid_renderizer:
  filename_extension: ['css', 'js']
  path: ['assets']
```

**Comment by yosymfony** [comment]
@jevets, @knorthfield Could you help me with the default values?

**Comment by knorthfield** [comment]
I think you've pretty much got it. I'd add .json as well. Maybe .svg if they get passed through the renderer.

**Comment by jevets** [comment]
I agree with @knorthfield , defaults look good. I'd rather it not try to do too much automatically, is easy enough to config per-project.

If I run into another worth considering as default, will create a new issue for discussion

**Comment by yosymfony** [comment]
Ok. This is ready. Thank you guys
