### ISSUE TITLE
Pagination does not respect sorting in list_mode

### ISSUE THREAD

**Issue by grahl** [spress/Spress#94]
As the title indicates, this always sorts ascending:

```
generator: "pagination"
provider: "site.posts"
list_mode: true
sort_by: "date"
sort_type: "descending"
```

While this works fine:

```
generator: "pagination"
provider: "site.posts"
sort_by: "date"
sort_type: "descending"
```

**Comment by yosymfony** [comment]
Hi @grahl, this is a subject of [Spresso theme](https://github.com/spress/Spress-theme-spress) repo, so if you can see in this [code](https://github.com/spress/Spress-theme-spresso/blob/master/src/content/index.html#L11), you can appreciate that paginated data is only used with `list_mode: false` (the default value)

**Comment by grahl** [comment]
Thanks!

**Comment by yosymfony** [comment]
@grahl many thanks
